name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CONFIGURE_PRESET: "default-release"

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        version: [ v3.4.4271-stable, dev ]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: seanmiddleditch/gha-setup-ninja@master
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Basic Dep Setup
        run:   |
               if [ "$RUNNER_OS" == "Linux" ]; then
                    sudo apt-get install libgl1-mesa-dev libglvnd-dev
                elif [ "$RUNNER_OS" == "Windows" ]; then
                    choco install wget
                    choco install unzip
               fi
        shell: bash
      - name: Setup QT
        run: |
          cd $HOME
          wget https://github.com/cxnder/qt-artifacts/releases/download/6.4.3/${{matrix.os}}.zip
          unzip ${{matrix.os}}.zip -d $HOME
        shell: bash
      - name: Update submodule
        run: |
          cd binaryninja-api
          git fetch --tags
          git checkout --force ${{matrix.version}}
      - name: Patch api to allow building headlessly
        run: |
          cd binaryninja-api
          git apply --ignore-whitespace --verbose ../api.patch
      - name: Configure CMake
        run: cmake --preset ${{env.CONFIGURE_PRESET}}-${{matrix.os}} -G Ninja
      - name: Build
        working-directory: ${{github.workspace}}/out/build
        run: cmake --build ${{env.CONFIGURE_PRESET}}-${{matrix.os}}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.os}}-${{matrix.version}}
          path: ${{github.workspace}}/out/build/${{env.CONFIGURE_PRESET}}-${{matrix.os}}/*callgraph*